env:
  node: true
  jest: true
parser: "@typescript-eslint/parser"
parserOptions:
  project: "./tsconfig.json"
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:prettier/recommended
overrides:
  - files:
      - "*.spec.ts"
    extends:
      - plugin:jest/all
      - plugin:jest/style
      - plugin:jest-formatting/strict
